travis:
  secure:
    BINSTAR_TOKEN: 34GhSh0EJUnHsC06kpwCdYZuchusNtqekHD/bclSnFHsLZBagLftxcu5B+ltLax5YN26TEEe8U2d67Jf6PRlR6dFXjiy9i90IR5CzFFYcYW1rXwNC0oro+w7gUylds7kmETDtVCAgjk/Ptp5n/TdhGXZt2lGDn9RcqWs6dRtt09pzW/kvZkr0LLOH4/1iUbxMuW9LfrBWS/hePYVawytWyPFCXWgB7lzn+UJyVktlDgMYF7U0YFBXUSUeFxCuYpWzZqzBzvYStM80eY5rg9DBGWrnXniVsOgeVrripCnLwPL1h4KdJFX//g787TEiVnZLnXtFxGxFwfjVaE+iQVg327MCYQ6MWlCrTGS86AT2k4AZcMMqwiQVEODDxxO/nJPqZfrd/CrfjWI+IEkJqKkk0puLVp8b5VWxksKnkLy560IgB5yly+97CkLifyNEVbBnKGuHPxY8tjuRQQnwzPcgbSSowMRH5wd/CKZtYrETpx4PggZrRl7VVTO3w1INUWuBsW3uCrVD93vBkSGdziWx/i8TD/jDldeSO58442ttALgDYdUNXfvtmyGPGsnP4cPfVupaHxXaO0rSxS5HXey9oXfhQ1bmDHk/UI2ziKDf3SzxsdmVD/pkULFfOD1aCMFDKac9Xdo+GwgFtRnGx6IHIE39yc7W3n2F1RV6eu3EpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
