travis:
  secure:
    BINSTAR_TOKEN: FAqPpOId81d4qoYluX5oBZYLH2knUIqPvYu+7gfA/dKN9kfyYVaW3TF2e/pBS5B3MmaJGiUOMmqHz55GE9yQkMfN1UmMJKWEpcr2/UnL3FrYFvBvWbskpzu54/BbbE2AZfEY/ywSbHlU0pE52GWLooZDsguK1nSQ3ntY2ohWg8MAxalcfDt6L+lvWTzpV8ORrg0LghHsA9gv6xfbzhqiHeLY489xaEhoFy3IK5OrN7iZcNWvlc53xZ09PBwQRd2qEEU6v5Al+iDAOdU3LTenMzH5iTQ/6MlFI9ujIxXW90uxBnwstiipAK1yaWgtdnE8VwPyI7cwYQsKagz47gld0tF3zyHKBadQstaM8gM/tqxzyOvatsSKCfFZ4DSfkM1Rx+XY3ZeFIGKiBnwwsabnWtPxb7I56vnyjejsJeokGmN4lbofrbhlDeorKTopxwtZhb52hycngAHble5DXLiCP1PGmakGGAIL5IbslnOxxfTctMNedLHIKyQXytUmC8znfU8yiMPIcBc4zYbyGRHaT74SILgUCogrdyWxBxmmTuzAarV1R1RjedpgQ/LBPWaP82CCmIYNcFB6cLU89xup0ohjbmUVnDsvJIgiGYM7fhC7g97Q8k5vOjCcNtoB646PcKO/w3vQ4nCyYurG7H2h2pVhdxMa7IjVk2GGlfQ1ZEg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
